// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsbnY1GGn4WgfOEc3G4fiuiaDnQSKQwI0',
    appId: '1:179769436216:android:f6ebe59b09cfcd07c55ecd',
    messagingSenderId: '179769436216',
    projectId: 'facebook-app-a83c7',
    storageBucket: 'facebook-app-a83c7.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeQ5PgNGueoSnB2VqJLntf1sVGelXZGQ',
    appId: '1:179769436216:web:83b33f982aff04c4c55ecd',
    messagingSenderId: '179769436216',
    projectId: 'facebook-app-a83c7',
    authDomain: 'facebook-app-a83c7.firebaseapp.com',
    storageBucket: 'facebook-app-a83c7.appspot.com',
    measurementId: 'G-0PLP6ZR05J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpP4x5hlCNJoxz1se3jARrBV4NPqmIBWc',
    appId: '1:179769436216:ios:eb32234abfe60e5fc55ecd',
    messagingSenderId: '179769436216',
    projectId: 'facebook-app-a83c7',
    storageBucket: 'facebook-app-a83c7.appspot.com',
    androidClientId: '179769436216-1pi83m13n59mpve9a7kifput1sj8c21j.apps.googleusercontent.com',
    iosClientId: '179769436216-1nbsh1leohciehocusvutinqh7971sso.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceAppV2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpP4x5hlCNJoxz1se3jARrBV4NPqmIBWc',
    appId: '1:179769436216:ios:eb32234abfe60e5fc55ecd',
    messagingSenderId: '179769436216',
    projectId: 'facebook-app-a83c7',
    storageBucket: 'facebook-app-a83c7.appspot.com',
    androidClientId: '179769436216-1pi83m13n59mpve9a7kifput1sj8c21j.apps.googleusercontent.com',
    iosClientId: '179769436216-1nbsh1leohciehocusvutinqh7971sso.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerceAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSeQ5PgNGueoSnB2VqJLntf1sVGelXZGQ',
    appId: '1:179769436216:web:b765ee0535b4b6e8c55ecd',
    messagingSenderId: '179769436216',
    projectId: 'facebook-app-a83c7',
    authDomain: 'facebook-app-a83c7.firebaseapp.com',
    storageBucket: 'facebook-app-a83c7.appspot.com',
    measurementId: 'G-GJ4EVDKWSK',
  );

}